apiVersion: apps/v1
kind: Deployment
metadata:
  name: siebel-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: siebel-service
  template:
    metadata:
      labels:
        app: siebel-service
    spec:
      containers:
      - name: siebel-service
        image: siebel-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: SQLALCHEMY_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: database-url

