apiVersion: apps/v1
kind: Deployment
metadata:
  name: real-time-pipeline
spec:
  replicas: 3
  selector:
    matchLabels:
      app: real-time-pipeline
  template:
    metadata:
      labels:
        app: real-time-pipeline
    spec:
      containers:
      - name: real-time-pipeline
        image: real-time-pipeline:latest
        ports:
        - containerPort: 8080
        env:
        - name: SQLALCHEMY_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: database-url